### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by smuteex** [smuteex/dinohost-wiki#1]
- [ ]  Mam lagi co robic
- [ ]  Podlaczenie wlasnej domeny
- [ ]  Bungeecord
- [ ]  Datapacki
- [ ]  AntyXray w silnik
- [ ]  Pregeneracja
- [ ]  Jak edytować pliki (configi)
- [ ]  Dlaczego nie ma spigota
- [ ]  Włączanie mapy z nowszej wersji na starszej wersji
- [ ]  Jak ustawić resourcepack dla wszystkich graczy
- [ ]  Co to harmonogram

**Comment by Fafikk** [comment]
- [ ] Opisać silniki
- [ ] Edytować poradnik o sftp

**Comment by Fafikk** [comment]
# Boty discord
- [ ] Podstawowy setup bota node.js
- [ ] Podstawowy setup bota python

**Comment by smuteex** [comment]
> # Boty discord
> 
>     * [ ]  Podstawowy setup bota node.js
> 
>     * [ ]  Podstawowy setup bota python

https://zxu.pl/?s=discord

**Comment by Fafikk** [comment]
co to jeszcze trzeba napisać
